spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_shop
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # bỏ chữ s thừa

vnpay:
  tmnCode: YOUR_TMN_CODE
  hashSecret: YOUR_SECRET_KEY
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay-return

jwt:
  secret: your-secret-key-at-least-32-characters-long
  expiration: 86400000   # 1 ngày, tính bằng milliseconds